name: release

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  pull_request:

jobs:
  package:
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
    uses: hamlet-io/.github/.github/workflows/engine_image_release.yml@1.1.4
    secrets: inherit
