name: release

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  pull_request:

jobs:
  uses: hamlet-io/.github/.github/workflows/engine_image_release.yml@main
  secrets: inherit
