name: release

on:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  pull_request:

jobs:
  image_release:
    uses: 'hamlet-io/.github/.github/workflows/engine_image_release.yml@1.1.2'
    secrets: inherit
